name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Preparar arquivos web
        run: npm run build

      - name: Criar projeto Android
        run: npx cap add android
      - name: Configurar ícone do aplicativo
        run: |
          mkdir -p android/app/src/main/res/mipmap-mdpi
          mkdir -p android/app/src/main/res/mipmap-hdpi
          mkdir -p android/app/src/main/res/mipmap-xhdpi
          mkdir -p android/app/src/main/res/mipmap-xxhdpi
          mkdir -p android/app/src/main/res/mipmap-xxxhdpi

          convert icon.png -resize 48x48 android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          convert icon.png -resize 72x72 android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          convert icon.png -resize 96x96 android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          convert icon.png -resize 144x144 android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          convert icon.png -resize 192x192 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

          cp android/app/src/main/res/mipmap-mdpi/ic_launcher.png android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
          cp android/app/src/main/res/mipmap-hdpi/ic_launcher.png android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
          cp android/app/src/main/res/mipmap-xhdpi/ic_launcher.png android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
          cp android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
          cp android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png

          rm -f android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
          rm -f android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
      - name: Sincronizar
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gerar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: Horas-Viagens29-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
